redis:
  image: redis:5.0.7-alpine
  container_name: cache
  ports:
    - 6379:6379
api:
  build: ./
  volumes:
    - ./:/usr/src/api/
  links:
    - redis
  ports:
    - 8080:8080
  env_file: ./.env
  command: 'npm run start:server'
worker:
  build: ./
  volumes:
    - ./:/usr/src/api/
  links:
    - redis
  env_file: ./.env
  command: 'npm run start:worker'
